### PR TITLE
Refactor version features

### PR DESCRIPTION
**Pull request by gkoz**
~~Rename the features to lower case to conform with Rust style. This is a
[breaking change]~~
Make version features recursive to avoid enumerating the versions
everywhere.
Update the readme and travis.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Are you sure that if I use a gtk 3.10 version, I'll have access to this [method](https://github.com/jeremyletang/rgtk/pull/252/files#diff-0a7b1346a2fb832b3bbea7dd5f966abaR125) for example ? And for the naming, I'm not sure this is needed. I'll wait @jeremyletang's opinion before doing anything on it if you don't mind.

**Comment by gkoz** [comment]
> Are you sure that if I use a gtk 3.10 version, I'll have access to this method for example ?

The recursive feature declarations in `Cargo.toml` take care of that. In particular, `gtktest` uses `MenuButton` which is under `feature = "gtk_3_6"` and builds fine with just `--features gtk_3_10`.

**Comment by gkoz** [comment]
The renaming we could just postpone I guess, it's not that important.

**Comment by gkoz** [comment]
Removed the renaming bit.

**Comment by GuillaumeGomez** [comment]
Perfect, I merge it. Thanks for your work !

**Pull request merged**
