### PR TITLE
Add a missing example crate to the build

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
We didn't add gtktest to the tests built because it cannot run under GTK 3.6. I was working on it. Look [here](https://github.com/GuillaumeGomez/rgtk/tree/cargo-example).

**Comment by gkoz** [comment]
Oh, sorry :)

**Comment by GuillaumeGomez** [comment]
No problem ! However, if you find the solution I'm looking for, I'd be very glad haha. I want to make only one Cargo.toml file for all examples in order to not rebuild rgtk every time (that's a pain in the ass !). The problem is that I don't know how to pass the GTK version to the rgtk Cargo file:

```Shell
> cd examples
> cargo build GTK_3_6
```

I asked and it was supposed to work but it's not.

**Comment by gkoz** [comment]
I'm not entirely sure I understood the problem, but take a look at how openssl handles passing features between crates: https://github.com/sfackler/rust-openssl/blob/master/openssl/Cargo.toml

**Comment by gkoz** [comment]
@GuillaumeGomez
I feel that examples should just follow the convention of belonging to the library crate and being built with `cargo test`. The versions problem could be handled with macros, see https://github.com/gkoz/rgtk/tree/version_macros
If someone's working on an example a lot, they could put it in a separate crate locally.

**Comment by GuillaumeGomez** [comment]
@gkoz: I have to test and confirm.

**Pull request closed without merging**
