### PR TITLE
Update pkg-config and gcc versions

### PR DESCRIPTION
**Pull request by oakes**
Not sure if it was just my setup, but I wasn't able to build until I bumped these library versions.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Hum... Travis fails. Have you tried with :

```Rust
pkg-config = "^0.0.0"
gcc = "^0.0.0"
```
?

**Comment by oakes** [comment]
Looks like Travis was just having issues. I did a force push without any changes and this time it passed.

**Comment by GuillaumeGomez** [comment]
Have you tried my solution ? Like that we won't have to change anything for a moment.

**Comment by oakes** [comment]
Looks like Travis is having a bad time. I changed it to our solution and now it's failing on the curl command.

**Comment by GuillaumeGomez** [comment]
Don't worry, it happens sometime... Just relaunch the test to make it (probably) work.

**Comment by GuillaumeGomez** [comment]
You see ? Random !

**Comment by oakes** [comment]
Yeah it looks like it will work now. Does ^0.0.0 just make it grab the latest version?

**Comment by GuillaumeGomez** [comment]
The last 0.x.y version, yes. It's explained in details [here](http://doc.crates.io/crates-io.html#using-crates.io-based-crates). Thanks for your work, I merge it !

**Pull request merged**
