### PR TITLE
Replace match...Err block with equivalent unwrap()

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for that ! I wait travis to confirm and I merge.

**Comment by frewsxcv** [comment]
Oh hold on, i'll fix that

**Comment by GuillaumeGomez** [comment]
Now that's good. Thanks for your work !

**Comment by gkoz** [comment]
Last I checked it wasn't actually equivalent, because the second part of result is a String instead of an Error. Look at the output in the failure mode.

**Comment by frewsxcv** [comment]
@gkoz I don't understand, can you elaborate your concerns?

**Comment by gkoz** [comment]
Make pkg-config fail and see what cargo build prints out.

**Comment by frewsxcv** [comment]
> Make pkg-config fail 

What do you mean by this?

**Comment by gkoz** [comment]
The match you replaced had two arms. Have you tested both scenarios after making the change and confirmed that in either of them the new code behaves in exactly the same way?

**Comment by frewsxcv** [comment]
It should functionally be the same, but it looks like it also adds extra text when it panics

https://github.com/rust-lang/rust/blob/ecf8c64e1b1b60f228f0c472c0b0dab4a5b5aa61/src/libcore/result.rs#L781

Feel free to revert my commit if you don't want that text to be shown

**Comment by gkoz** [comment]
Note the `{:?}` there? The match used `{}` and it makes a difference in this case, because debug formatting of `String` isn't very readable. It becomes fairly obvious when you test the failure mode of the build script.

**Comment by GuillaumeGomez** [comment]
Sorry @frewsxcv but I have to revert your PR. Thanks @gkoz.

**Comment by frewsxcv** [comment]
All good, sorry for the confusion. Keep up the great work with this project

**Comment by GuillaumeGomez** [comment]
@frewsxcv No problem. Don't hesitate to add anymore stuff, this project is far to be finished and any help is very appreciated !

**Comment by gkoz** [comment]
I've discussed this issue on IRC and the sentiment is that `unwrap` should only be used when it's not expected to panic therefore the end users aren't supposed to see the output it produces. If we, like in this case, want to panic, better do it explicitly.

**Pull request merged**
