### PR TITLE
Add myself to the authors and put license headers where they're missing

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
The use of LGPL for this crate code worries me though. The fact that crates other than rustc libs are linked to the applications statically, likely causes the GPL to infect the whole finished application which probably is not the intended outcome. Right now it seems to me that to avoid this problem Rust bindings could be licensed under MIT/BSD/whatever but make it clear that the resulting application will link to an LGPL library.

**Comment by GuillaumeGomez** [comment]
You're not the first one who talk to me about this. I had the same comment on the IRC two days ago. I'm not confident with licenses at all but I did speak about it with @jeremyletang (normally, he's available again from the next week). I proposed to him the MIT license but it didn't go any further. So yes, a change in the license will occur very soon.

**Comment by gkoz** [comment]
As there aren't a lot of authors the license change seems possible. I wonder if Mozilla legal could be to persuaded give their opinion on the issue of LGPL and Rust crates. :)

**Comment by GuillaumeGomez** [comment]
I didn't think about that... Well, maybe. Any tips for asking them this (and contacting them too by the way) ?

**Comment by gkoz** [comment]
I doubt that they'll respond in a meaningful way to a direct inquiry. It might be worthwhile to raise the question on discuss or reddit and if a significant number of people show interest, the Rust developers might feel compelled to get some info out of Mozilla (or at least comment on feasibility of dynamic linking some crates which could make this a moot point).

**Comment by GuillaumeGomez** [comment]
I opened a topic in reddit [here](http://www.reddit.com/r/rust/comments/30b38n/what_license_to_choose/).

**Pull request merged**
