### PR TITLE
Use to_bool and to_gboolean instead of ifs and matches

### PR DESCRIPTION
**Pull request by gkoz**
This should make the code a bit more readable and fixes at least one copypasting mistake.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
That's right that we thought about doing it from a long time now. So thank you for this PR and your contribution !

**Comment by gkoz** [comment]
There's `gtk::traits::recent_chooser` remaining with this kind of match I'm not sure about:
```rust
unsafe { ffi::gtk_recent_chooser_set_show_private(GTK_RECENT_CHOOSER(self.get_widget()), match show_private {
true => ffi::GTRUE,
false => ffi::GTRUE
}) }
```

**Comment by GuillaumeGomez** [comment]
Hum... I think this is an error. Replace it with to_gboolean please. I'll merge your PR after your change.

**Comment by gkoz** [comment]
Done.

**Comment by GuillaumeGomez** [comment]
Thanks a lot ! Waiting for travis and it's merged !

**Pull request merged**
