### PR TITLE
Move the examples to a single crate

### PR DESCRIPTION
**Pull request by gkoz**
Add macros to gtktest to stub out any code that uses GTK 3.10 when building for an older version.
Fix various warnings in other examples.
Let travis do less repeated building of the same crates.

### CODE REVIEW

**Comment by gkoz** [comment]
I don't get one thing though... Why use a bleeding edge ppa and build with GTK_3_6 only?

**Comment by GuillaumeGomez** [comment]
You mean on travis ?

**Comment by gkoz** [comment]
Yes. It should be able to build `GTK_3_14` too

**Comment by GuillaumeGomez** [comment]
Look [here](https://travis-ci.org/jeremyletang/rgtk/builds/52811821#L565).

**Comment by gkoz** [comment]
So... you're getting the development files from a system repo and that additional ppa is useless because it doesn't have libgtk3-dev?

**Comment by GuillaumeGomez** [comment]
Yes. And that's very annoying.

**Comment by gkoz** [comment]
Any objections? This makes travis builds three times faster ;)

**Comment by GuillaumeGomez** [comment]
None ! I was waiting for it !

**Pull request merged**
