### PR TITLE
Update to work with latest rust nightly

### PR DESCRIPTION
**Pull request by maurizi**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for your work but it seems the rust compiler is broken. Can you report the failure please ? When it'll be fixed, I'll merge your PR.

**Comment by maurizi** [comment]
Compiler bug has been reported: https://github.com/rust-lang/rust/issues/20555

**Comment by GuillaumeGomez** [comment]
Nice, we just have to wait now.

**Comment by maurizi** [comment]
I played a bit more with this tonight, and I think this needs quite a bit more work.  Closing for now.

**Pull request closed without merging**
