### PR TITLE
Split glib off into its own crate

### PR DESCRIPTION
**Pull request by gkoz**
This was much easier.
But we need to do something about the examples, travis tests are taking way too long.. :-P

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Isn't it ? For the examples, I started to work on that [here](https://github.com/GuillaumeGomez/rgtk/tree/cargo-example). But as you can see, this is a very old work. But that's the idea. i did the same on another repo of mine.

**Comment by gkoz** [comment]
Eh, I've looked at that branch but couldn't quite figure out what you did there :) Could you point to specific commits maybe?

**Comment by GuillaumeGomez** [comment]
The simpler will be a little explanation (which is quite simple). I wanted to create two Cargo files: one for rgtk and one for the examples. The problem I encountered was that I couldn't figure out how to pass the gtk version to the rgtk cargo file through the examples cargo file. Otherwise, it was done.

I hope I didn't lost you... Sorry if my explanations aren't clear.

**Comment by gkoz** [comment]
You can pass the features like this: https://github.com/jeremyletang/rgtk/blob/master/Cargo.toml#L14-19
Having a second crate would still double the compilation times...

**Comment by GuillaumeGomez** [comment]
At first, we only had one cargo file. But my computer was overheating when building it and @jeremyletang found the compilation too long so we splitted the lib and the examples' compilations. A little too much however. We'll always have to have the double compilation time, but only once after that.

**Comment by gkoz** [comment]
Fair enough. :) Further separation of the crates should make the times more manageable though.

As to this PR, I've spotted a blemish, I think, I'll tweak the commit a bit...

**Comment by gkoz** [comment]
Done. When working on the wrappers redesign I've found that this crate needs a major rehaul too: I wasn't able to use `List` as is for interacting with `libgtk`...

**Comment by gkoz** [comment]
That last change was actually wrong. Backed it out.

**Comment by GuillaumeGomez** [comment]
All is good. I merge it. Thanks !

**Pull request merged**
