### PR TITLE
Add more version and one os gate

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
You want me to wait before merging ? If you have other version handdling, just add them here. Anyway, thanks for your work once again !

**Comment by gkoz** [comment]
The different PRs shouldn't conflict with each other I think. There's one more in my queue adding cairo versions but it waits on the versions refactoring for now. ;)
Merging all of those allows builds on Windows to succeed. There wasn't anything major blocking Windows support actually.

**Comment by GuillaumeGomez** [comment]
The *only* problem was no one used windows actually haha.

**Comment by gkoz** [comment]
Yeah I don't fancy using it as well but fixing the build from time to time should be doable. I'll prepare some installation steps to put in the readme.

**Comment by GuillaumeGomez** [comment]
That'd be very nice !

**Pull request merged**
