### PR TITLE
Fix the build

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Once again I was doing it. We should really try to figure a way to prevent the other before starting. ^^

**Comment by gkoz** [comment]
We could designate an issue e.g. #7 for reporting all the build breakages and fixes in progress.
Or IRC, some IM, what have you.
I hope you're not fixing the warning as well ;)

**Comment by GuillaumeGomez** [comment]
No, you started it so you finish it (punishment !).

**Comment by gkoz** [comment]
I'm not sure I'll process all the deprecated stuff quickly, so might make sense to just merge these fixes for now.

**Comment by gkoz** [comment]
Cleaned up more wrong and deprecated stuff. Should be good to merge.

**Comment by GuillaumeGomez** [comment]
Once again, very nice job. By the way, you should add youself to the `Cargo.toml` authors. I totally forgot that and you did a lot more than enough to be in it !

**Comment by gkoz** [comment]
Right, I forgot about that too. :)

**Comment by GuillaumeGomez** [comment]
Make a PR for it !

**Pull request merged**
