### PR TITLE
Patch up CVec breakage

### PR DESCRIPTION
**Pull request by gkoz**
For now pretend to have unique pointers. There needs to be a CSlice probably.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I was about to do a PR for that actually haha. I'll take yours. I wait travis and then I merge.

**Comment by gkoz** [comment]
Had to fix the examples too...

**Comment by GuillaumeGomez** [comment]
You should have say it, I did the examples before knowing you had open this PR... Whatever, thanks ! Is it ok to merge now ?

**Comment by gkoz** [comment]
Sorry for duplicate effort. This one should be good, yes.
I also have an upcoming PR to move all of the examples to a single crate at last, those build times are just too annoying.

**Comment by GuillaumeGomez** [comment]
I totally agree. If you find the solution of _THE_ problem, then it's even more perfect ! I can't wait to see how you will do that !

**Pull request merged**
