### PR TITLE
Fixes for cairo::Context::set_dash and get_dash

### PR DESCRIPTION
**Pull request by SimonSapin**
Please see individual commit messages, and confirm that the test fails on the second commit and is fixed on the third. I was not able to run tests locally.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Uh, it looks like cairotest didn’t fail on Travis at the second commit like I expected. Either this test is not actually run, or I don’t understand what’s going on.

https://travis-ci.org/jeremyletang/rgtk/builds/49418200

**Comment by GuillaumeGomez** [comment]
Thanks for your contribution ! We're just compiling on travis, not testing.
We test on our computers.

**Comment by SimonSapin** [comment]
Oh, I see. Travis runs `cd ../cairotest && cargo build`, not `&& cargo run`

**Comment by GuillaumeGomez** [comment]
It would be difficult since it's a graphic software...

2015-02-04 7:36 GMT+01:00 Simon Sapin <notifications@github.com>:

> Oh, I see. Travis runs cd ../cairotest && cargo build, not && cargo run
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeremyletang/rgtk/pull/190#issuecomment-72798330>.
>



-- 
*web CV : www.guillaume-gomez.fr <http://www.guillaume-gomez.fr>*
*portable: +33 6 21 92 31 88*

**Comment by SimonSapin** [comment]
Yeah, I understand. I just made an incorrect assumption when first looking at the results.

**Comment by GuillaumeGomez** [comment]
No problem. I'll take a look at your PR this evening.

**Pull request merged**
