### PR TITLE
Fix an error and some warnings

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
Meh, need to fix one more error with the latest nightly.

**Comment by GuillaumeGomez** [comment]
Once again, you did the same thing as me (I actually didn't finish it but I started haha). Thanks !

**Comment by gkoz** [comment]
I dunno. I typically make several branches on top of each other locally but only one of them can be sent as a pull request. So something done two days ago might not be visible here until the parent branch is merged into master letting me do the next pull request. Maybe we could improve this process.

**Comment by GuillaumeGomez** [comment]
I didn't open a PR because it wasn't finished yet.

**Comment by gkoz** [comment]
I guess I got used to you not having time to tinker on this stuff. Should communicate more :)

**Comment by GuillaumeGomez** [comment]
Yes I should but I don't have time so when I can, I just do some little stuff like that and don't think about communicating around. Even more since I don't know how many time it will takes...

**Pull request merged**
