### PR TITLE
Move the low level bindings into separate crates

### PR DESCRIPTION
**Pull request by gkoz**
This isn't polished yet and may be buggy but at least it builds.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Very nice work on that. I wait @jeremyletang's confirmation to merge it.

**Comment by gkoz** [comment]
I'll look it over once more then to try and catch silly mistakes and oversights.

**Comment by GuillaumeGomez** [comment]
Ok ! Notify us when it's done then.

**Comment by gkoz** [comment]
I've cleaned it up. Please review.

**Comment by GuillaumeGomez** [comment]
Fine for me. @jeremyletang ?

**Comment by gkoz** [comment]
Added two more commits that move higher-level functionality out of the sys crates.

**Comment by GuillaumeGomez** [comment]
Once again, good job ! @jeremyletang ?

**Comment by gkoz** [comment]
Maybe `glib-sys` should as well be `glib2-sys`...

**Comment by GuillaumeGomez** [comment]
Well, I didn't find the gtk3-sys that good actually... Why not justkeeping gtk-sys and glib-sys ?

**Comment by gkoz** [comment]
Because `libgtk2` is still a thing and there is software built against it and the GTK docs prominently designate the current version as `GTK+ 3`. It also seems in a bad taste to put out a crate "xxx" if it only supports a subset of widely available "libxxx" versions.
Apparently `glib 1.2` is still around too although confusion is less likely.

**Comment by oakes** [comment]
Is this still on track to be merged? Looks like there are conflicts now. I'm excited for this, because I'd love to add support for libvte as a separate crate.

**Comment by GuillaumeGomez** [comment]
It is. I was waiting for @jeremyletang's opinion but I guess I'll have to do without it... Can you update your PR @gkoz, please ?

**Comment by gkoz** [comment]
Rebased. The tests are affected by the broken nightly from yesterday right now.

**Comment by GuillaumeGomez** [comment]
Weird bug... At least, I'll wait for it to be solved.

**Comment by oakes** [comment]
It looks like Travis still has the rust version with the broken cargo.

**Comment by gkoz** [comment]
Travis is probably going to get stuck on `*mut cairo::ffi::cairo_rectangle_list_t` being `!Send` now which is unrelated to this change. BTW, why did nobody tell me there needs to be a `cairo-sys`? ;)

**Comment by GuillaumeGomez** [comment]
I thought it was. I didn't pay enough attention, my bad.

**Comment by gkoz** [comment]
I think it's ready.

**Comment by GuillaumeGomez** [comment]
Very impressive work. I merge it. Thanks !

**Comment by oakes** [comment]
Great work! It turns out I can't create a separate crate for my vte stuff, because you can't use macros across crate boundaries (I use struct_Widget, check_pointer, etc). So, I'll keep it in my fork until I figure out a solution to that.

**Comment by gkoz** [comment]
@oakes
Here's my current model for moving forward with the wrappers and casts reform if you're interested: https://github.com/gkoz/rgtk/tree/convert/gtk3
There's a half-working basic example (signals aren't there yet).

**Pull request merged**
